// Mock CSS module for testing
export default {
  staffContainer: 'staffContainer',
  disabled: 'disabled',
  interactiveArea: 'interactiveArea',
  cursorDefault: 'cursorDefault',
  cursorPointer: 'cursorPointer',
  cursorCrosshair: 'cursorCrosshair',
  cursorNotAllowed: 'cursorNotAllowed',
  hoverPreview: 'hoverPreview',
  fadeIn: 'fadeIn',
  fadeOut: 'fadeOut',
  noteSelected: 'noteSelected',
  noteDeselected: 'noteDeselected',
  validationCorrect: 'validationCorrect',
  validationIncorrect: 'validationIncorrect',
  validationMissing: 'validationMissing',
  validationOverlay: 'validationOverlay',
  validationMessage: 'validationMessage',
  success: 'success',
  error: 'error',
  partial: 'partial',
  loading: 'loading',
};